### ISSUE TITLE
Ive been completely taken over! HELP!!!!

### ISSUE THREAD

**Issue by ApoMyles** [EthanMcBloxxer/ethanmcbloxxer.github.io#28]
<h/> HELP PLEASE!!!!!!!!!!<h>
I've really been trying to get rid of a pest, That's taken over laptop. I really believe they gained access through, Microsoft Edge. Im not sure what information you will require on my part, But I'll be sure to keep tabs on this security breach Issue, Thank You, Sir/Mam, Prompt reply would relly Be gratly appreciated , due to the seroisness of the issue at hand
https://www.dropbox.com/trial_first?cont=install&signup_tag=index_web&suggested_product_family=plus @

**Comment by EthanMcBloxxer** [comment]
From what I can understand, you may have a RAT on your computer.
If you have an antivirus solution, please do a "full" scan and remedy any threats that are found through it. If not, open Windows Security (by pressing the start button at the bottom of your screen and typing "Windows Security", then Enter), click on Virus & threat protection, then either select "More options" on each threat or click "Scan options", select "Full scan", and then click Scan now.
After all of this is accomplished, you should see something a bit like this on your window:
![sLERDP 1](https://user-images.githubusercontent.com/39684348/107055443-4f21ac80-679f-11eb-808e-bdcd20d46b82.png)
